### PR TITLE
First Template version

### PR DESCRIPTION
**Pull request by SebasF1349**
The first template version to test.

### CODE REVIEW

**Comment by endigo9740** [comment]
@SebasF1349 you're going to know this better than myself, so if you feel comfortable you should have admin access to merge. Just tap the green "Merge Pull Request" option and it should merge this into `main` and be visible for everyone.

Totally find if we want it put it out there and listen for feedback from others too.

Thanks bud!

**Comment by SebasF1349** [comment]
Asked in discord if someone can test it works as expected, just in case. I will leave it for a few days and then merge. Also the readme probably needs a grammar revision.

**Comment by endigo9740** [comment]
I'll aim to jump in and review on Sunday if someone doesn't get to it soon. Thanks!

**Comment by endigo9740** [comment]
Thanks for handling this @SebasF1349

**Pull request merged**
